---
wifi_ssid: 'SSID_NAME'
wifi_password: 'PASSWORD_STR'

# Generated in browser @ https://esphome.io/components/api.html?highlight=randomly%20generated
ha_api_key: 'rXHVAoMWifG9rWoG5IthjWy83mao7BLCA5Qr8FBgD60='
ota_password: 'OTA_PASSWORD_STR'